client:client.o chat_login.o run_form.o analyse_msg.o
	gcc -o client client.o chat_login.o run_form.o analyse_msg.o
client.o:client.c
	gcc -c client.c
chat_login.o:chat_login.c
	gcc -c chat_login.c
run_form.o:run_form.c
	gcc -c run_form.c
analyse_msg.o:analyse_msg.c
	gcc -c analyse_msg.c
